### ISSUE TITLE
Remove ToDo bug

### ISSUE THREAD

**Issue by jamesgeorge007** [jamesgeorge007/vueToDo#4]
> The scenario is:-

The user has the provision to remove all tasks or any specific one as required. Tapping the ```Remove All``` button removes all of them by mutating the state (Emptying the array). While, the ```Remove``` button corresponding to each task removes the specific task by index.

When the ```Remove All``` button is tapped, a ```msg``` property within the state is set to '''Everything has been removed``` which is set back to none when a task is added thereafter. This is what intended for the ```Remove``` button as well which doesn't mutate the corresponding property within the state.

When the user removes each and every task with the corresponding button, the message should show up!

**Comment by OuKevin** [comment]
I can pick this up. To clarify, you want the message to be similar to the Remove all message if the last task is removed with the individual Remove button?

**Comment by OuKevin** [comment]
Also, right now the Remove All button sets the msg property to "'They have been removed!" and not "Everything has been removed" as mentioned in the initial post. Does the text need to be updated as well?

**Comment by jamesgeorge007** [comment]
@OuKevin Do you have something which brings more sense?

**Comment by OuKevin** [comment]
Looks good to me 👍
